language: rust
dist: xenial
os: linux
rust: stable
env:
  global:
    - MAKEFLAGS="-j 2"
before_install:
  - |
    if [ -n "$YARA_VERSION" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://github.com/VirusTotal/yara/archive/v$YARA_VERSION.tar.gz
      tar xzf v$YARA_VERSION.tar.gz
      cd yara-$YARA_VERSION
      ./bootstrap.sh && ./configure
      make
      sudo make install
      sudo ldconfig -v
      cd ..
    fi
script:
  - cargo build --verbose --no-default-features --features "$YARA_FEATURES"
  - cargo test --verbose --no-default-features --features "$YARA_FEATURES"
jobs:
  include:
    - env:
        - YARA_VERSION=4.0.5
        - YARA_FEATURES=bindgen
    - rust: nightly
      env:
        - YARA_VERSION=4.0.5
        - YARA_FEATURES=bindgen
    - env:
        - YARA_VERSION=4.0.5
        - YARA_FEATURES=bundled-4_0
    - rust: nightly
      env:
        - YARA_VERSION=4.0.5
        - YARA_FEATURES=bundled-4_0
  #  - env:
  #      - YARA_FEATURES=vendored,bindgen
  #  - rust: nightly
  #    env:
  #      - YARA_FEATURES=vendored,bindgen
  #  - os: windows
  #    env:
  #      - YARA_FEATURES=vendored,bindgen
  allow_failures:
    - rust: nightly
  fast_finish: true
