language: rust
dist: xenial
os: linux
rust:
  - stable
  - nightly
env:
  global:
    - MAKEFLAGS="-j 2"
  jobs:
    - YARA_VERSION=4.1.0  YARA_FEATURES=bindgen
    - YARA_VERSION=4.1.0  YARA_FEATURES=bundled-4_1_0
    -                     YARA_FEATURES=vendored,bindgen
    -                     YARA_FEATURES=vendored,bundled-4_1_0
before_install:
  - |
    if [ -n "$YARA_VERSION" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://github.com/VirusTotal/yara/archive/v$YARA_VERSION.tar.gz
      tar xzf v$YARA_VERSION.tar.gz
      cd yara-$YARA_VERSION
      ./bootstrap.sh && ./configure
      make
      sudo make install
      sudo ldconfig -v
      cd ..
    fi
script:
  - cargo build --verbose --no-default-features --features "$YARA_FEATURES"
  - cargo test --verbose --no-default-features --features "$YARA_FEATURES";
jobs:
  include:
    - os: windows
      rust: stable
      env: YARA_FEATURES=vendored,bindgen
    - os: windows
      rust: stable
      env: YARA_FEATURES=vendored,bundled-4_1_0

  allow_failures:
    - rust: nightly
  fast_finish: true
