language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - MAKEFLAGS="-j 2"
  jobs:
    - YARA_VERSION=3.7.1
    - YARA_VERSION=3.11.0
before_install:
  - wget https://github.com/VirusTotal/yara/archive/v$YARA_VERSION.tar.gz
  - tar xzf v$YARA_VERSION.tar.gz
  - cd yara-$YARA_VERSION
  - ./bootstrap.sh && ./configure
  - make
  - sudo make install
  - sudo ldconfig -v
  - cd ..
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
