name: bindings

on:
  push:
    paths:
      - yara-sys/yara
      - yara-sys/build.rs
      - yara-sys/wrapper.h
  pull_request:
    paths:
      - yara-sys/yara
      - yara-sys/build.rs
      - yara-sys/wrapper.h

jobs:
  bindings:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            family: "unix"
          - os: "windows-latest"
            family: "windows"
    runs-on: ${{ matrix.os }}
    steps:
      # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        if: matrix.os == 'windows-latest'
        with:
          version: "14.0"
          directory: ${{ runner.temp }}/llvm
      - name: Set LIBCLANG_PATH
        if: matrix.os == 'windows-latest'
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Generate bindings
        shell: bash
        run: |
          cargo build --verbose --no-default-features --features vendored,bindgen
          mkdir out
          find -name 'bindings.rs'
          cp "$(find -name 'bindings.rs')" "./out/yara-${{ matrix.family }}.rs"
          ls out
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.family }}
          path: |
            out
